---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[cepheus::default]
    attributes:
