#!/bin/bash
#
# Copyright 2017, LambdaStack
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##########
# NOTE: If you run this script and receive a VBoxManage related error then most likely the VM(s) have been removed or
# missing from where you store VirtualBox VMs BUT VBoxManage still thinks they are there. Simply pull up the
# VirtualBox UI application, stop and remove the 'ceph-*' VMs that should be shown and then start this script again.
##########

# Exit immediately if anything goes wrong, instead of making things worse.
set -eu

clear

echo "             __     "
echo "             \ \    "
echo "              > \   "
echo "             / ^ \  "
echo "            /_/ \_\ "
echo
echo "            Cepheus Vagrant Build"
echo "-----------------------------------------------------"
echo "Bootstrapping local CEPH environment using Vagrant..."
echo

# Creates the REPO_ROOT env var for everything else to use...
export REPO_ROOT=$(git rev-parse --show-toplevel)

# Default values...
export CEPH_DEV_MODE=0
export CHEF_CEPHEUS_DEBUG=0
export BOOTSTRAP_GET_PREREQS_ONLY=0
export BOOTSTRAP_REMOVE_PREREQS=0
export BOOTSTRAP_HTTP_PROXY=
export BOOTSTRAP_HTTPS_PROXY=
export BUILD_VMS_ONLY=0
export BUILD_ENVIRONMENT=vagrant
export BUILD_LOCATION=public
export BUILD_DATA_CENTER=local
export BUILD_OS=centos
export BUILD_UPDATE=1

# NB: May want to add an option for 'build' or 'update' so only the template_engine runs and the files can then be
# uploaded to Chef for management.

while getopts cbglrsvu:n:e:d:p:o:t: opt; do
    case $opt in
        b)
            # (optional) Builds the local Vagrant VMs only - skips building the Ceph portion. Used during development
            # to help save some time.
            export BUILD_VMS_ONLY=1
            ;;
        c)
            # (optional) Allows you to see Chef output that only happens when Chef debug flags are set.
            # VERY verbose. The (-v below) option is meant for `bash` verbose and not Chef. You can combine both.
            CHEF_KNIFE_DEBUG="-VV"
            CHEF_CLIENT_DEBUG="-l debug"

            ;;
        d)
            # (optional) NB: Use this option if you want to change the default 'data center' from `local` to something
            # like `data_center_nyc`. It MUST represent a sub-folder in `private` or `public`!
            export BUILD_DATA_CENTER=$OPTARG

            # NB: ./CEPH_UP -d data_center_nyc
            ;;
        e)
            # (optional) NB: Use this option if you want to change the default environment from `vagrant` to something
            # like `production`. Can be used with -l option to change from `public` to `private`
            export BUILD_ENVIRONMENT=$OPTARG

            # NB: ./CEPH_UP -e production
            ;;
        g)
            # (optional) -g to simply get the prerequisites and exit. Use it with (-r below) and it will remove the
            # prerequisites and download them again.
            export BOOTSTRAP_GET_PREREQS_ONLY=1
            ;;
        l)
            # (optional) NB: Use this option if you want to change from the default `public` to `private` for 'location'.
            export BUILD_LOCATION=private
            ;;
        n)
            # (optional) NB: Use this option if you need to test/debug ceph-chef. It will skip downloading the current
            # version of ceph-chef so the local version will be used. The best way to do this is to copy over
            # your modified version of ceph-chef to the cookbook directory in this project before running
            # this script.

            # BOOTSTRAP_VAGRANT_DEBUG=1
            # CEPH_DEV_MODE == 1 then install ceph github source along with development tools. You can also install your favorite IDE if you want.
            # If nothing is passed in with -d option the CEPH_DEV_MODE is empty and debug ceph-chef is used.
            export CEPH_DEV_MODE=$OPTARG
            export CHEF_CEPHEUS_DEBUG=1

            # NB: Requires at least 1 argument '0' or '1'
            # Example: ./CEPH_UP -n 0
            ;;
        o)
            # (optional) NB: Use this option if you want to change from the default OS of `centos` to `rhel` or `ubuntu`
            export BUILD_OS=$OPTARG
            ;;
        p)
            # (optional) Only used if your environment requires a proxy to access the outside world.
            export BOOTSTRAP_HTTP_PROXY=$OPTARG
            export BOOTSTRAP_HTTPS_PROXY=$OPTARG
            ;;
        r)
            # (optional) -r to remove the prerequisites. Cleaning up.
            # It does not exit like -g but is called before gathering prerequisites.
            # Use it with -g -r and it will clean up and gather updated prerequisites and exit based on versions in build.yaml
            export BOOTSTRAP_REMOVE_PREREQS=1
            ;;
        s)
            # (optional) Used to skip building local Vagrant VMs build and jump right to building out Ceph. Used during
            # development to help save some time.
            BOOTSTRAP_SKIP_VMS=1
            ;;
        t)
            BOOTSTRAP_TYPE=$OPTARG
            ;;
        u)
            # Update the cluster. If nothing exists to update then it will build/create it for the first time.
            export BUILD_UPDATE=$OPTARG
            ;;
        v)
            # (optional) Verbose of `bash` commands - not Chef output
            set -x
            ;;
    esac
done

# Create *initial* build.yaml from common.yaml
cp $REPO_ROOT/data/common.yaml $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/build.yaml

# Build bootstrapping environment based on yaml data
BUILD=data/build.sh
echo "====> Generating $REPO_ROOT/$BUILD from $REPO_ROOT/data/common.yaml..."
$REPO_ROOT/data/templates/template_engine -d $REPO_ROOT/data/common.yaml -i $REPO_ROOT/data/templates/$BUILD.j2 -o $REPO_ROOT/$BUILD
sudo chmod +x $REPO_ROOT/$BUILD

## WIP Section
# Pass data templates through template enginge first
# BUILD_DATA_TEMPLATES=data/data_templates.sh
# echo "====> Generating $REPO_ROOT/$BUILD_DATA_TEMPLATES from $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/data_templates.yaml..."
# $REPO_ROOT/data/templates/template_engine -d $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/data_templates.yaml -i $REPO_ROOT/data/templates/$BUILD_DATA_TEMPLATES.j2 -o $REPO_ROOT/$BUILD_DATA_TEMPLATES
# sudo chmod +x $REPO_ROOT/$BUILD_DATA_TEMPLATES
#
# # This must now be ran to generate environment.yaml for the given environment.
# echo "====> Executing $REPO_ROOT/$BUILD_DATA_TEMPLATES"
# source $REPO_ROOT/$BUILD_DATA_TEMPLATES
##

# Add all other data files to the final build.yaml
BUILD_DATA=data/data_files.sh
echo "====> Generating $REPO_ROOT/$BUILD_DATA from $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/data/environment.yaml..."
$REPO_ROOT/data/templates/template_engine -d $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/data/environment.yaml -i $REPO_ROOT/data/templates/$BUILD_DATA.j2 -o $REPO_ROOT/$BUILD_DATA
sudo chmod +x $REPO_ROOT/$BUILD_DATA


## Execution phase of scripts - after being built above!
# Data portion is executed first to create the required data files.
# Execute the freshly built `data_files.sh` script that was just built from the template.
#
echo "====> Executing $REPO_ROOT/$BUILD_DATA"
source $REPO_ROOT/$BUILD_DATA
#
# Execute the freshly built `build.sh` script that was just built from the template.
echo "====> Executing $REPO_ROOT/$BUILD"
source $REPO_ROOT/$BUILD
#
## Execution phase end block


# Build the init and update scripts
BUILD_INIT_UPDATE=data/build_init_update.sh
echo "====> Generating $REPO_ROOT/$BUILD_INIT_UPDATE from $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/build.yaml..."
$REPO_ROOT/data/templates/template_engine -d $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/build.yaml -i $REPO_ROOT/data/templates/$BUILD_INIT_UPDATE.j2 -o $REPO_ROOT/$BUILD_INIT_UPDATE
sudo chmod +x $REPO_ROOT/$BUILD_INIT_UPDATE
echo "====> Executing $REPO_ROOT/$BUILD_INIT_UPDATE"
source $REPO_ROOT/$BUILD_INIT_UPDATE

# Build environments file for Chef
echo "====> Generating $REPO_ROOT/environments/$BUILD_ENVIRONMENT.json..."
$REPO_ROOT/data/templates/template_engine -d $REPO_ROOT/data/$BUILD_LOCATION/$BUILD_DATA_CENTER/build.yaml -i $REPO_ROOT/data/templates/base_environment.json.j2 -o $REPO_ROOT/environments/$BUILD_ENVIRONMENT.json

# Configure and test any proxies configured.
if [[ ! -z $BOOTSTRAP_HTTP_PROXY ]] || [[ ! -z $BOOTSTRAP_HTTPS_PROXY ]] ; then
  echo "====> Testing configured proxies..."
  source $REPO_ROOT/bootstrap/common/bootstrap_proxy_setup.sh
fi

# Do prerequisite work prior to starting build, downloading files and
# creating local directories. It can do one of two things - download or execute commands. The end result is a filled cache.
echo "====> Downloading necessary files to local cache..."
source $REPO_ROOT/bootstrap/common/bootstrap_prereqs.sh

# If prerequisites only then end after getting them
if [[ $BOOTSTRAP_GET_PREREQS_ONLY -ne 0 ]]; then
    echo
    echo "====> Prerequisites have been updated and exiting."
    echo
    exit 1
fi

# If the environment is for vagrant and BUILD_UPDATE is > 0 then execute the vagrant build environment. If BUILD_UPDATE is
# 0 then only the other options will be applied. If BUILD_UPDATE is 2 then the vagrant vms will be built and the cepheus
# environment will automatically get built to make things easier. Or, you can set $BUILD_UPDATE to 1 and then it will only
# build the vagrant vms and then prepare the bootstrap for building out the other cluster like in a production environment.
if [[ $BUILD_ENVIRONMENT == "vagrant" && $BUILD_UPDATE -ne 0 ]]; then
    cd $REPO_ROOT/bootstrap/vms/vagrant
    ./CEPH_UP_VAGRANT
    exit 0
fi

# Build out or update the given environment.
echo "====> Calling cepheus_bootstrap_init.sh..."
sudo $REPO_ROOT/bootstrap/common/cepheus_bootstrap_init.sh $REPO_ROOT $BUILD_LOCATION $BUILD_DATA_CENTER

echo "====> Calling bootstrap_chef_server.sh..."
TMP_REPO_ROOT=$REPO_ROOT
source $REPO_ROOT/bootstrap/common/bootstrap_chef_server.sh $REPO_ROOT

echo "====> Calling cepheus_build_update.sh..."
source $TMP_REPO_ROOT/bootstrap/common/cepheus_build_update.sh
