#!/bin/bash
#
# Copyright 2017, LambdaStack
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# NOTE: AUTOGENERATED FILE. Only modify template version.

# Exit immediately if anything goes wrong!
set -eu

# Create directory for download cache.
CACHE_ISO=isos
CACHE_RPM=rpms
CACHE_DEB=debs
CACHE_PYTHON=python
CACHE_LOADER=loaders
CACHE_COOKBOOK=cookbooks
CACHE_GEM=gems

# If set then it will remove the cache directories
if [[ $BOOTSTRAP_REMOVE_PREREQS -ne 0 ]]; then
    rm -rf $HOME/.ceph-cache
fi

# Create the cache directories...
mkdir -p $HOME/.ceph-cache/cobbler/{$CACHE_ISO,$CACHE_LOADER}
mkdir -p $HOME/.ceph-cache/{$CACHE_PYTHON,$CACHE_RPM,$CACHE_DEB,$CACHE_COOKBOOK,$CACHE_GEM}

# download_file wraps the usual behavior of curling a remote URL to a local file
# NOTE: PROXY - Make sure your http_proxy and https_proxy envrionment variables are set correctly if behind a proxy.
download_file() {
  FILE=$1
  URL=$2

  if [[ ! -f $HOME/.ceph-cache/$FILE && ! -f $HOME/.ceph-cache/${FILE}_downloaded ]]; then
    echo $FILE
    echo $URL

    rm -f $HOME/.ceph-cache/$FILE
    curl -L --progress-bar -o $HOME/.ceph-cache/$FILE $URL
    touch $HOME/.ceph-cache/${FILE}_downloaded
  fi
}

# NOTE: PROXY - Make sure your ftp_proxy envrionment variable is set correctly if behind a proxy.
ftp_file() {
  FILE=$1
  URL=$2

  if [[ ! -f $HOME/.ceph-cache/$FILE && ! -f $HOME/.ceph-cache/${FILE}_downloaded ]]; then
    echo $FILE
    echo $URL

    rm -f $HOME/.ceph-cache/$FILE
    wget $URL -O $HOME/.ceph-cache/$FILE
    touch $HOME/.ceph-cache/${FILE}_downloaded
  fi
}

git_clone_or_update() {
  local NAME=$1
  local URL=$2

  echo "===> Git clone or update..."
  if [[ ! -f $HOME/.ceph-cache/${NAME}_downloaded ]]; then
    if [[ ! -d $HOME/.ceph-cache/$NAME ]]; then
      git clone $URL $HOME/.ceph-cache/$NAME || true
    else
      ( cd $HOME/.ceph-cache/$NAME && git pull --ff-only $URL )
    fi
    touch $HOME/.ceph-cache/${NAME}_downloaded
  fi
}

# Obtain an RHEL 7.2 image to be used for PXE booting in production.
echo "===> Downloading ISO..."
if [[ ! -z $COBBLER_BOOTSTRAP_ISO ]]; then
  if [[ $COBBLER_DOWNLOAD_ISO -eq 1 ]]; then
    # NOTE: the +e is because the hardware  We can change it later...
    set +e
    download_file cobbler/isos/centos-7-x86_64-minimal.iso http://mirror.es.its.nyu.edu/centos/7/isos/x86_64/CentOS-7-x86_64-Minimal-1611.iso
    set -e
  fi
fi

if [[ ! -z $COBBLER_BOOTSTRAP_ISO ]]; then
  download_file cobbler/loaders/pxelinux.0 http://cobbler.github.io/loaders/pxelinux.0-3.86
  download_file cobbler/loaders/menu.c32 http://cobbler.github.io/loaders/menu.c32-3.86
  download_file cobbler/loaders/grub-x86.efi http://cobbler.github.io/loaders/grub-0.97-x86.efi
  download_file cobbler/loaders/grub-x86_64.efi http://cobbler.github.io/loaders/grub-0.97-x86_64.efi
fi

echo "===> Downloading Chef..."
download_file /rpms/chef-12.19.36-1.el7.x86_64.rpm https://packages.chef.io/files/stable/chef/12.19.36/el/7/chef-12.19.36-1.el7.x86_64.rpm
download_file /rpms/chef-server-core-12.13.0-1.el7.x86_64.rpm https://packages.chef.io/files/stable/chef-server/12.13.0/el/7/chef-server-core-12.13.0-1.el7.x86_64.rpm

# BIRD is a little different
echo "===> Downloading Bird..."
ftp_file /rpms/bird-1.5.0-1.x86_64.rpm ftp://bird.network.cz/pub/bird/redhat/bird-1.5.0-1.x86_64.rpm

# Most important cookbook
# If set then it will not download but remove from cache and use the development version that should be set in the cepheus/cookbooks directory.
if [[ $CHEF_CEPHEUS_DEBUG -eq 0 ]]; then
  echo "===> Downloading ceph-chef..."
  download_file cookbooks/ceph-chef-1.1.4.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/ceph-chef/versions/1.1.4/download
else
  # Remove it so it's not used.
  echo "===> Removing ceph-chef cache and using *debug* version of Ceph-Chef..."
  rm -f $HOME/.ceph-cache/cookbooks/ceph-chef-*
fi

if [[ $CEPH_DEV_MODE -ne 0 ]]; then
  echo "===> Cloning Ceph..."
  git_clone_or_update github/ceph https://github.com/ceph/ceph.git
fi

# Python
download_file /python/PyYAML-.tar.gz http://pyyaml.org/download/pyyaml/PyYAML-3.12.tar.gz

# Cookbooks
download_file cookbooks/poise-2.7.2.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/poise/versions/2.7.2/download
download_file cookbooks/chef-client-7.2.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/chef-client/versions/7.2.0/download
download_file cookbooks/windows-2.1.1.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/windows/versions/2.1.1/download
download_file cookbooks/ohai-5.0.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/ohai/versions/5.0.0/download
download_file cookbooks/cron-4.1.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/cron/versions/4.1.0/download
download_file cookbooks/logrotate-2.1.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/logrotate/versions/2.1.0/download
download_file cookbooks/compat_resource-12.16.3.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/compat_resource/versions/12.16.3/download
download_file cookbooks/ntp-3.3.1.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/ntp/versions/3.3.1/download
download_file cookbooks/yum-5.0.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/yum/versions/5.0.0/download
download_file cookbooks/yum-epel-2.1.1.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/yum-epel/versions/2.1.1/download
download_file cookbooks/apt-6.0.1.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/apt/versions/6.0.1/download
download_file cookbooks/apache2-3.2.2.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/apache2/versions/3.2.2/download
download_file cookbooks/chef_handler-2.1.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/chef_handler/versions/2.1.0/download
download_file cookbooks/firewall-2.5.4.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/firewall/versions/2.5.4/download
download_file cookbooks/chef-sugar-3.4.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/chef-sugar/versions/3.4.0/download
download_file cookbooks/sudo-3.3.1.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/sudo/versions/3.3.1/download
download_file cookbooks/collectd-2.2.4.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/collectd/versions/2.2.4/download
download_file cookbooks/collectd_plugins-2.1.3.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/collectd_plugins/versions/2.1.3/download
download_file cookbooks/poise-service-1.4.2.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/poise-service/versions/1.4.2/download
download_file cookbooks/yumgroup-0.5.0.tar.gz http://cookbooks.opscode.com/api/v1/cookbooks/yumgroup/versions/0.5.0/download

# Gems
# REQUIRED for ceph-chef cookbook - must be installed before doing 'sudo chef-client' on any node
download_file gems/netaddr-1.5.1.gem https://rubygems.org/downloads/netaddr-1.5.1.gem
download_file gems/chef-sugar-3.4.0.gem https://rubygems.org/downloads/chef-sugar-3.4.0.gem

# Pull needed gems for fpm
GEMS=( arr-pm-0.0.10 backports-3.6.4 cabin-0.7.1 childprocess-0.5.6 clamp-0.6.5 ffi-1.9.8 fpm-1.3.3 json-1.8.2 )
# mkdir -p $HOME/.ceph-cache/gems
for GEM in ${GEMS[@]}; do
  download_file gems/$GEM.gem https://rubygems.global.ssl.fastly.net/gems/$GEM.gem
done

# Pull knife-acl gem. This is ONLY needed if using data bags where the data bag is created with a recipe!
download_file gems/knife-acl-0.0.12.gem https://rubygems.global.ssl.fastly.net/gems/knife-acl-0.0.12.gem