#
# Author:: Chris Jones <chris.jones@lambdastack.io>
# Cookbook Name:: cepheus
#
# Copyright 2017, LambdaStack
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

include_recipe 'cepheus::ceph-conf'

# NB: This recipe is code generated by the template_engine during the build/update process.
if node['cepheus']['method'] == 'pxe'
    # NOTE: May want to move mount and import to install later...

    bash 'import-distro-distribution-pxe_boot' do
      user 'root'
      code <<-EOH
        mount -o loop /tmp/centos-7-x86_64-minimal.iso /mnt
        cobbler import --name=centos-7.3 --path=/mnt --breed=redhat --arch=x86_64
        cobbler distro edit --name=centos-7.3-x86_64 --kopts="ksdevice= inst.repo=http://10.0.100.20/cblr/ks_mirror/centos-7.3-x86_64"
        umount /mnt
      EOH
      not_if "cobbler distro list | grep centos-7.3"
      only_if "test -f /tmp/centos-7-x86_64-minimal.iso"
    end

    # NOTE: By default, cobbler import above will create a profile with the name of the import + arch
    # Distro was added so no need to edit it.
    # Leave the initial profile (minimal settings) that was created automatically on the distro import and then copy from it create a profile to match the profile data

    bash 'profile-update-pxe_boot' do
      user 'root'
      code <<-EOH
            cobbler profile copy --name=centos-7.3-x86_64 --newname=ceph_osd_node
            cobbler profile edit --name=ceph_osd_node --kickstart=/var/lib/pxe_boot/kickstarts/ceph_osd_node.ks --kopts="interface=auto"
            cobbler profile edit --name=ceph_osd_node --netboot-enabled=True --comment="OSD type nodes either dedicated OSD or converged with other services like MON and RGW." --name-servers="8.8.8.8" "8.8.4.4"
        
            cobbler profile copy --name=centos-7.3-x86_64 --newname=ceph_non_osd_node
            cobbler profile edit --name=ceph_non_osd_node --kickstart=/var/lib/pxe_boot/kickstarts/ceph_non_osd_node.ks --kopts="interface=auto"
            cobbler profile edit --name=ceph_non_osd_node --netboot-enabled=True --comment="NON-OSD type nodes. Services like MON, RGW or MDS." --name-servers="8.8.8.8" "8.8.4.4"
        

      EOH
      only_if "cobbler profile list"
      only_if "test -f /tmp/centos-7-x86_64-minimal.iso"
    end

    # Set up a default system - you will need to add the information via cobbler system edit on the cli to match your environment
    # Also, do cobbler system add for every ceph node with mac, IP, etc OR modify the json data used by cobbler and then restart cobbler
    node['cepheus']['servers'].each do | server |
      if !server.roles.include? 'bootstrap'
        bash 'add-to-pxe_boot' do
          user 'root'
          code <<-EOH
            cobbler system add --name=#{server['name']} --profile=#{server['profile']}
          EOH
          not_if "cobbler system list | grep #{server['name']}"
          only_if "cobbler profile list | grep #{server['profile']}"
        end
      end
    end

    # Update the interfaces for each node
    # NB: May want to add bonding options...
    node['cepheus']['servers'].each do | server |
        server['interfaces'].each do | interface |
          # IMPORTANT: This version sets the --if-gateway of the cluster interface to "" so that ARP does not cause a race condition!
          bash "update-pxe_boot-macs-#{server['name']}" do
            user 'root'
            code <<-EOH
                cobbler system edit --name=#{server['name']} --static=#{server['static']} --interface=#{interface['interface']} --mac=#{interface['mac']} --ip-address=#{interface['ip']} --netmask=#{interface['netmask']} --if-gateway=#{interface['pxe_gateway']} --mtu=#{interface['mtu']}
            EOH
            only_if "cobbler system list | grep #{server['name']}"
          end
        end
    end

    # Cobbler will create the base pxe boot files needed. Every time you modify profile/system/distro you will need to do a pxe_boot sync
    execute 'pxe_boot-sync' do
        command lazy{ "cobbler sync" }
        only_if "test -f /tmp/centos-7-x86_64-minimal.iso"
    end

    # The block below is done for non-vagrant environments
    if node['cepheus']['environment'] != 'vagrant'
        directory '/tmp/postinstall' do
            mode 0700
            recursive true
            action :create
            not_if "test -d /tmp/postinstall"
        end

        # NOTE: The /tmp/postinstall must exist
        execute 'tar-postinstall' do
            command lazy { "tar -zcvf /var/www/cobbler/pub/postinstall.tar.gz /tmp/postinstall/" }
            not_if "test -f /var/www/cobbler/pub/postinstall.tar.gz"
        end

        # Get the validate.pem and install client.rb into /var/www/cobbler/pub
        bash 'copy-chef-node' do
            user 'root'
            code <<-EOH
                sudo cp /etc/opscode/cepheus-validator.pem /var/www/cobbler/pub/validation.pem
                sudo chmod 0644 /var/www/cobbler/pub/validation.pem
            EOH
        end

        template '/var/www/cobbler/pub/client.rb' do
            source 'client.rb.erb'
            mode '0644'
        end

        # NOTE: The kickstart process creates the directories, wgets the files to the node's /etc/chef and sets the permissions.
        # It then runs chef-client to verify
    end
end
